### PR TITLE
push tags before sha, only if tag doesn't exist

### LINKED ISSUE #60: ecs-conex and tags
A moment ago I committed be77d88112aa9c057b4cbe98043352b7c58295d2, tagged it as `v0.2.0` and then `git push && git push --tags`.

These two pushes resulted in two conex jobs, but the ECR repository **did not** end up with an image tagged with the git sha -- only the `v0.2.0` image exists. My hunch is that because the two images are identical, ECR doesn't retain both? This could lead to a botched deploy if the deploy tool assumes that it can use the sha in the stack's `GitSha` parameter.

I'm not sure if there's a way to mitigate this, maybe we just need to document the behavior?

cc @emilymdubois @yhahn @emilymcafee

### PR DESCRIPTION
**Pull request by perrygeo**
Resolves #60 

@rclark this is still WIP but can you take a look and see if this is on the right track?

### CODE REVIEW

**Comment by rclark** [comment]
Yep this looks great! If you can just follow up by tweaking the test scripts we'll be 🏅 

I think this whole thing could be refactored better, into:
- a function that pushes any given tag / sha to all the ecr regions
- a function that checks if the commit we're on matches a tag
- an integration function that contains the "if tag/sha exists in region" conditions, and calls the other two functions appropriately.

... but that can always happen on another pass.

**Comment by perrygeo** [comment]
@rclark ready to roll

**Comment by perrygeo** [comment]
Deployed to staging and sent a message through - hitting the `fatal: could not read Password for 'https://github.com'` error that @dnomadb mentions here https://github.com/mapbox/ecs-conex/pull/77#issuecomment-257052333 - maybe just due the github token not having permissions? Not sure how to proceed with testing, @rclark ?

**Comment by rclark** [comment]
Post #81, please try rebasing this over master and testing on staging again.

**Comment by perrygeo** [comment]
confirmed on staging, pushes both a gitsha-tagged image and a tag-tagged image to the registry. Anything else we need to check on staging @rclark ?

**Comment by rclark** [comment]
Nope! Please add some notes to the changelog and then merge. I owe some changelog notes from work I did yesterday as well. Maybe we tag once we land #77 also.

**Pull request merged**
