### PR TITLE
Adds NPMToken stack param

### PR DESCRIPTION
**Pull request by emilymdubois**
This PR adds an `NPMToken` stack parameter, creates an npmrc file before building, and deletes the npmrc file after the image has successfully finished. The npmrc file is a prerequisite to install private npm modules in the pushing repository.

@rclark, I think this should work if it's run before the [`docker build` step](https://github.com/mapbox/ecs-conex/blob/8b96a95aa2e27f7b92fa6ff5edd4cfd827ddfd56/ecs-conex.sh#L138-L139). Would love your thoughts on this.

cc @willwhite @emilymcafee @yhahn

### CODE REVIEW

**Comment by rclark** [comment]
This fixes #27

**Comment by emilymdubois** [comment]
Tested these changes with a manual deploy and successfully created images from a repo with a private npm module.

@yhahn wanna take a quick 👀 and see if this is good for merging?

**Comment by yhahn** [comment]
@emilymdubois looks good, :ship: !

**Comment by emilymdubois** [comment]
@rclark @yhahn do you think I should add a null default value for NPMAccessToken in the CFN template to make it an optional parameter, or is it 👌 as-is?

**Comment by willwhite** [comment]
I think it's good to have this required. As npm private modules become more and more prevalent I don't think there is a good use case for not providing a valid token on every conex stack. The main downside of having it required is it forces the assumption that you're using node on any user of ecs-conex.

**Comment by rclark** [comment]
> The main downside of having it required is it forces the assumption that you're using node on any user of ecs-conex.

This is a very good argument for not making the parameter required. I'd rather see a default value here than a required parameter.

**Pull request merged**
